"""Adverse event evidence layer.

Converts free-text adverse event evidence from completed trials into validated,
provenance-bearing event objects, and evaluates versioned phenotype definitions
over them.  All data handled by this package is synthetic and generated by the
repository itself.
"""

__version__ = "0.1.0"
