"""HTTP API.

Thin. Every endpoint delegates to the same pipeline the CLI uses, so the API and
the CLI cannot disagree about which definition version produced a number.

Three things this API does deliberately:

**Attributes carry their route.** Every record and episode response says which
variable each value came from and by which method, because in this layer that is
part of the fact rather than metadata about it.

**Discovery and cohort selection are different endpoints.** ``/retrieve``
returns adjudicated episodes; ``/discover`` returns candidates and says so in
the payload. No parameter turns one into the other.

**There is no approval gate.** ``/agent/ask`` compiles, executes, and returns
the trace. What makes a number checkable is that it can be followed back to
source afterwards, by someone who was not in the room.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, Optional

import yaml
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from . import paths
from .catalog import ConfigError
from .ingest import IngestError
from .knowledge import KnowledgeRegistry, ScopeRequired, diff_definitions
from .phenotype.loader import DefinitionError
from .pipeline import Pipeline
from .profiles import ProfileError
from .runs import ManifestStore, ReplayError, ResultStore, execute

NOTICE = (
    "All data is synthetic and generated by this repository. The extraction "
    "backend is a configurable rule and lexicon baseline unless an LLM backend "
    "was configured; it is not a trained clinical NLP model. Coded terms in the "
    "concept catalogue are illustrative placeholders, not licensed dictionary "
    "content."
)

app = FastAPI(
    title="Adverse event evidence layer",
    version="3.0.0",
    description=(
        "One clinical attribute, five possible homes, one provenance-bearing "
        "shape, and versioned phenotype definitions evaluated over it. " + NOTICE
    ),
)


@lru_cache(maxsize=1)
def _pipeline_singleton() -> Pipeline:
    return Pipeline.load(store_path=paths.STORE_DB)


def get_pipeline() -> Pipeline:
    try:
        return _pipeline_singleton()
    except (IngestError, ConfigError, ProfileError) as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


def reset_pipeline() -> None:
    _pipeline_singleton.cache_clear()


def _runs_dir() -> Path:
    return paths.RUNS_DIR


def _manifests() -> ManifestStore:
    return ManifestStore(_runs_dir())


def _results() -> ResultStore:
    return ResultStore(_runs_dir() / "results")


def _gold_version(pipeline: Pipeline, definition_id: str) -> Optional[int]:
    """The version the corpus's answer key was written against.

    Defaulting to the highest published version would quietly evaluate a
    different definition from the one the gold labels describe, and the numbers
    would read as a regression rather than as a different question.
    """
    recorded = str(pipeline.store.manifest.get("gold_case_definition") or "")
    if recorded.startswith(f"{definition_id}.v"):
        try:
            return int(recorded.rsplit(".v", 1)[-1])
        except ValueError:
            return None
    return None


def _attribute(attribute: Any) -> dict[str, Any]:
    return {
        "value": attribute.value,
        "availability": attribute.availability,
        "method": attribute.method,
        "source": attribute.source,
        "source_variable": attribute.source_variable,
        "confidence": attribute.confidence,
        "note": attribute.note,
        "prior_availability": attribute.prior_availability,
        "evidence": [s.model_dump(mode="json") for s in attribute.evidence],
    }


# --------------------------------------------------------------------------
# Requests
# --------------------------------------------------------------------------


class BuildRequest(BaseModel):
    refresh: bool = False


class EvaluateRequest(BaseModel):
    definition_id: str = "te_truncal_rash"
    version: Optional[int] = None
    studies: list[str] = Field(default_factory=list)
    allow_draft: bool = False
    save: bool = True


class AskRequest(BaseModel):
    question: str
    backend: Literal["deterministic", "llm"] = "deterministic"
    save: bool = True


class CandidateRequest(BaseModel):
    definition_id: str
    base_version: int
    changes: dict[str, Any] = Field(default_factory=dict)
    author: str = "ui"


# --------------------------------------------------------------------------
# Corpus
# --------------------------------------------------------------------------


@app.get("/api/summary")
def summary() -> dict[str, Any]:
    import collections

    pipeline = get_pipeline()
    records = pipeline.records()
    return {
        **pipeline.summary(),
        "studies": pipeline.store.studies(),
        "profiles": {
            profile.profile_id: {
                "study_id": profile.study_id,
                "label": profile.label,
                "reported_term_style": profile.reported_term_style,
                "location_home": profile.home_kinds("location"),
                "pattern_home": profile.home_kinds("pattern"),
                "sponsor_variable": profile.sponsor_variable_name,
                "dictionary_version": profile.dictionary_version,
                "carries_both_location": profile.carries_both("location"),
                "note": profile.note,
            }
            for profile in pipeline.profiles.profiles.values()
        },
        "attribute_catalogues": {
            name: catalogue.value_ids()
            for name, catalogue in pipeline.catalog.attributes.items()
        },
        "location_routes": dict(sorted(collections.Counter(
            r.location.method or r.location.availability for r in records
        ).items())),
        "notice": NOTICE,
    }


@app.post("/build")
def build(request: BuildRequest) -> dict[str, Any]:
    """Normalize, extract, reconcile, index — the whole path."""
    pipeline = get_pipeline()
    records = pipeline.records(refresh=request.refresh)
    episodes = pipeline.episodes(refresh=request.refresh)
    index = pipeline.index(refresh=request.refresh)
    violations = [
        {"record_id": r.source_record_id, "attributes": r.missing_provenance()}
        for r in records if not r.has_full_provenance()
    ]
    return {
        "records": len(records),
        "episodes": len(episodes),
        "mentions": index.meta().mention_count,
        **pipeline.versions(),
        "provenance_violations": violations,
        "backend_notes": list(pipeline.engine().notes),
    }


@app.get("/api/records")
def records(
    profile: Optional[str] = None,
    availability: Optional[str] = None,
    method: Optional[str] = None,
    limit: int = Query(50, le=500),
) -> dict[str, Any]:
    pipeline = get_pipeline()
    rows = pipeline.records()
    if profile:
        rows = [r for r in rows if r.profile == profile]
    if availability:
        rows = [r for r in rows if r.location.availability == availability]
    if method:
        rows = [r for r in rows if r.location.method == method]
    return {
        "count": len(rows),
        "records": [
            {
                "source_record_id": r.source_record_id,
                "study_id": r.study_id,
                "subject_id": r.subject_id,
                "profile": r.profile,
                "reported_term": r.reported_term.value,
                "coded_event": r.coded_event.value,
                "dictionary_version": r.dictionary_version,
                "concept": r.standardized_concept,
                "location": r.location.value,
                "location_method": r.location.method,
                "location_source": r.location.source_variable,
                "location_availability": r.location.availability,
            }
            for r in rows[:limit]
        ],
    }


@app.get("/api/records/{source_record_id}")
def record(source_record_id: str) -> dict[str, Any]:
    pipeline = get_pipeline()
    found = next(
        (r for r in pipeline.records() if r.source_record_id == source_record_id),
        None,
    )
    if found is None:
        raise HTTPException(status_code=404, detail=f"no record {source_record_id!r}")
    documents = pipeline.store.documents_of(source_record_id)
    return {
        "record": found.model_dump(mode="json"),
        "attributes": {
            name: _attribute(attribute)
            for name, attribute in found.attributes().items()
        },
        "documents": [
            {"doc_id": d.doc_id, "kind": d.kind, "text": d.full_text}
            for d in documents
        ],
        "supplemental": pipeline.store.supplemental_for(source_record_id),
        "provenance_complete": found.has_full_provenance(),
    }


@app.get("/api/episodes")
def episodes(
    profile: Optional[str] = None,
    concept: Optional[str] = None,
    review_only: bool = False,
    limit: int = Query(50, le=500),
) -> dict[str, Any]:
    pipeline = get_pipeline()
    rows = pipeline.episodes()
    if profile:
        rows = [e for e in rows if e.profile == profile]
    if concept:
        rows = [e for e in rows if e.standardized_concept == concept]
    if review_only:
        rows = [e for e in rows if e.linkage_review_required]
    return {
        "count": len(rows),
        "episodes": [
            {
                "episode_id": e.episode_id,
                "study_id": e.study_id,
                "subject_id": e.subject_id,
                "profile": e.profile,
                "concept": e.standardized_concept,
                "location": e.location.value,
                "location_method": e.location.method,
                "location_source": e.location.source_variable,
                "location_availability": e.location.availability,
                "onset_offset_days": e.onset_offset_days.value,
                "source_record_ids": list(e.source_record_ids),
                "linkage_rule": e.linkage_rule,
                "linkage_review_required": e.linkage_review_required,
                "linkage_note": e.linkage_note,
            }
            for e in rows[:limit]
        ],
    }


@app.get("/api/episodes/{episode_id}")
def episode(episode_id: str) -> dict[str, Any]:
    pipeline = get_pipeline()
    found = next(
        (e for e in pipeline.episodes() if e.episode_id == episode_id), None
    )
    if found is None:
        raise HTTPException(status_code=404, detail=f"no episode {episode_id!r}")
    by_id = {r.source_record_id: r for r in pipeline.records()}
    return {
        "episode": found.model_dump(mode="json"),
        "attributes": {
            name: _attribute(attribute)
            for name, attribute in found.attributes().items()
        },
        "records": [
            by_id[r].model_dump(mode="json")
            for r in found.source_record_ids if r in by_id
        ],
    }


@app.get("/api/trajectories/{subject_id}")
def trajectory(subject_id: str) -> dict[str, Any]:
    pipeline = get_pipeline()
    found = pipeline.trajectories().get(subject_id)
    if found is None:
        raise HTTPException(status_code=404, detail=f"no subject {subject_id!r}")
    return found.model_dump(mode="json")


# --------------------------------------------------------------------------
# Definitions
# --------------------------------------------------------------------------


@app.get("/definitions")
def definitions() -> dict[str, Any]:
    pipeline = get_pipeline()
    return {
        "definitions": [
            {
                "id": d.id, "version": d.version, "key": d.key, "status": d.status,
                "label": d.label, "description": d.description,
                "hash": d.definition_hash,
                "accept_methods": sorted(
                    {m for r in d.required_attributes for m in r.accept_methods}
                ),
                "body": d.model_dump(mode="json"),
            }
            for d in pipeline.definitions.all()
        ]
    }


@app.get("/definitions/{definition_id}/{version}/yaml", response_class=PlainTextResponse)
def definition_yaml(definition_id: str, version: int) -> str:
    pipeline = get_pipeline()
    try:
        definition = pipeline.definitions.get(definition_id, version, allow_draft=True)
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return Path(definition.source_path).read_text(encoding="utf-8")


@app.get("/definitions/{definition_id}/compare")
def definition_compare(
    definition_id: str, left: int, right: int,
    scope: Optional[str] = Query(
        default=None,
        description=(
            "Required. The scientific question this comparison serves; the "
            "capability is for evidence reuse, not for auditing past choices."
        ),
    ),
) -> dict[str, Any]:
    pipeline = get_pipeline()
    try:
        a = pipeline.definitions.get(definition_id, left, allow_draft=True)
        b = pipeline.definitions.get(definition_id, right, allow_draft=True)
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    try:
        comparison = diff_definitions(
            a, b, pipeline.snapshot_id, scope,
            pipeline.evaluate(a), pipeline.evaluate(b),
        )
    except ScopeRequired as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return comparison.to_dict()


@app.post("/definitions/candidate")
def definition_candidate(request: CandidateRequest) -> dict[str, Any]:
    """Render a proposed next version as YAML, without writing anything."""
    pipeline = get_pipeline()
    try:
        base = pipeline.definitions.get(
            request.definition_id, request.base_version, allow_draft=True
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    body = base.model_dump(
        mode="json", exclude={"definition_hash", "source_path"}, by_alias=True
    )
    next_version = pipeline.definitions.next_version(base.id)
    body["version"] = next_version
    body["status"] = "draft"
    body["supersedes"] = base.key
    body["authors"] = [request.author]

    applied: list[str] = []
    for path, value in sorted(request.changes.items()):
        if _apply_change(body, path, value):
            applied.append(f"{path} = {value!r}")
        else:
            raise HTTPException(
                status_code=400, detail=f"no such definition path: {path!r}"
            )
    from .models import PhenotypeDefinition

    try:
        PhenotypeDefinition.model_validate(body)
    except Exception as exc:
        raise HTTPException(
            status_code=400, detail=f"the proposed candidate does not validate: {exc}"
        ) from exc
    return {
        "base": base.key,
        "candidate_version": next_version,
        "filename": f"{base.id}.v{next_version}.yaml",
        "applied_changes": applied,
        "yaml": yaml.safe_dump(body, sort_keys=False, allow_unicode=True),
        "note": (
            f"This is a candidate. {base.key} is {base.status} and has not been "
            f"modified. Save this file into config/phenotypes/ to publish it."
        ),
    }


def _apply_change(body: dict[str, Any], path: str, value: Any) -> bool:
    """Set one dotted path inside a definition body.

    A requirement is addressed by name — ``required_attributes.location.in`` —
    rather than by list index, so a candidate keeps its meaning if the order
    changes. The leaf must already exist: a change that invents a key is a typo
    in the caller's path, and adding it silently would produce a candidate that
    differs from the one asked for.
    """
    parts = path.split(".")
    node: Any = body
    for part in parts[:-1]:
        if isinstance(node, list):
            if part.isdigit() and int(part) < len(node):
                node = node[int(part)]
                continue
            match = next(
                (item for item in node
                 if isinstance(item, dict) and item.get("name") == part),
                None,
            )
            if match is None:
                return False
            node = match
            continue
        if isinstance(node, dict) and part in node:
            node = node[part]
            continue
        return False

    leaf = parts[-1]
    if isinstance(node, dict) and leaf in node:
        node[leaf] = value
        return True
    if isinstance(node, list) and leaf.isdigit() and int(leaf) < len(node):
        node[int(leaf)] = value
        return True
    return False


# --------------------------------------------------------------------------
# Evaluation, retrieval, harnesses
# --------------------------------------------------------------------------


@app.post("/evaluate")
def evaluate(request: EvaluateRequest) -> dict[str, Any]:
    pipeline = get_pipeline()
    try:
        definition = pipeline.definition(
            request.definition_id, request.version, allow_draft=request.allow_draft
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    manifest, assignments = execute(
        pipeline, definition, studies=request.studies or None, actor="api",
        manifest_store=_manifests(), result_store=_results(), save=request.save,
    )
    if request.save:
        pipeline.index().record_assignments(assignments)
    return {
        "manifest": manifest.model_dump(mode="json"),
        "assignments": [a.model_dump(mode="json") for a in assignments],
        "not_ascertainable": [
            a.model_dump(mode="json") for a in assignments
            if a.verdict == "not_ascertainable"
        ],
    }


@app.get("/retrieve")
def retrieve_endpoint(
    concept: Optional[str] = None,
    region: Optional[str] = None,
    location: list[str] = Query(default=[]),
    method: list[str] = Query(default=[]),
    profile: list[str] = Query(default=[]),
    studies: list[str] = Query(default=[]),
    verdict: list[str] = Query(default=[]),
    window_min: Optional[int] = None,
    window_max: Optional[int] = None,
    top_k: int = Query(50, le=1000),
) -> dict[str, Any]:
    """The precise path: adjudicated episodes, usable as a cohort."""
    from .retrieval.query import retrieve

    pipeline = get_pipeline()
    window = (
        (window_min, window_max)
        if window_min is not None and window_max is not None else None
    )
    try:
        result = retrieve(
            pipeline.index(), pipeline.catalog, concept=concept, region=region,
            location=location or None, method=method or None,
            profile=profile or None, studies=studies or None,
            verdict=verdict or None, window=window, top_k=top_k,
        )
    except ConfigError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return result.to_dict()


@app.get("/discover")
def discover_endpoint(
    text: Optional[str] = None,
    attribute: list[str] = Query(default=[]),
    profile: list[str] = Query(default=[]),
    unnormalized_only: bool = False,
    mode: Literal["lexical", "dense", "hybrid"] = "lexical",
    top_k: int = Query(50, le=1000),
) -> dict[str, Any]:
    """The discovery path: text mentions, every one a candidate."""
    from .retrieval.query import discover

    pipeline = get_pipeline()
    result = discover(
        pipeline.index(), pipeline.catalog, text=text,
        attribute=attribute or None, profile=profile or None,
        unnormalized_only=unnormalized_only, mode=mode, top_k=top_k,
    )
    return result.to_dict()


@app.get("/eval/silver")
def silver_endpoint(
    attribute: str = "location", limit: int = Query(25, le=500)
) -> dict[str, Any]:
    """Extraction scored against the study's own structured field."""
    from .silver import SilverHarness

    pipeline = get_pipeline()
    harness = SilverHarness(pipeline.configs, pipeline.store, pipeline.engine())
    eligible = harness.eligible_profiles(attribute)
    if not eligible:
        raise HTTPException(
            status_code=400,
            detail=(
                f"no profile records {attribute} both structurally and in text, "
                f"so there is nothing to build a silver standard from"
            ),
        )
    report = harness.run(pipeline.records(), attribute, eligible)
    body = report.to_dict()
    body["adjudication_queue"] = report.adjudication_queue()[:limit]
    return body


@app.get("/eval/transport")
def transport_endpoint(
    holdout: list[str] = Query(default=[]),
    definition_id: str = "te_truncal_rash",
    version: Optional[int] = None,
) -> dict[str, Any]:
    from .eval.transport import transportability

    pipeline = get_pipeline()
    try:
        definition = pipeline.definition(
            definition_id,
            version if version is not None
            else _gold_version(pipeline, definition_id),
        )
        return transportability(pipeline, definition, holdout or None)
    except (DefinitionError, ValueError) as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.get("/eval/ablation")
def ablation_endpoint(
    definition_id: str = "te_truncal_rash", version: Optional[int] = None
) -> dict[str, Any]:
    from .eval.harness import EvaluationHarness

    pipeline = get_pipeline()
    try:
        definition = pipeline.definition(
            definition_id,
            version if version is not None
            else _gold_version(pipeline, definition_id),
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return EvaluationHarness.build(pipeline, definition).ablation()


# --------------------------------------------------------------------------
# Agent
# --------------------------------------------------------------------------


@app.get("/agent/tools")
def agent_tools() -> dict[str, Any]:
    """The agent's entire callable surface, with schemas and permissions."""
    from .agent.tools import AgentServices

    return {
        "tools": AgentServices.catalogue(),
        "note": (
            "Every call is validated against its input schema before it runs "
            "and its output schema before it returns. There is no SQL surface "
            "and no tool that writes to a source record."
        ),
    }


@app.post("/agent/compile")
def agent_compile(request: AskRequest) -> JSONResponse:
    from .agent import AgentSession

    session = AgentSession(get_pipeline(), request.question, backend=request.backend)
    result = session.compile()
    payload = result.to_dict()
    payload["executed"] = False
    return JSONResponse(payload, status_code=200 if result.spec else 409)


@app.post("/agent/ask")
def agent_ask(request: AskRequest) -> JSONResponse:
    """Compile and execute, and return the trace that makes it checkable."""
    from .agent import AgentSession

    session = AgentSession(get_pipeline(), request.question, backend=request.backend)
    result = session.compile()
    if result.needs_clarification:
        return JSONResponse(
            {
                "executed": False,
                "clarification": result.clarification.model_dump(mode="json"),
                "detail": (
                    "The question leaves a rule underdetermined. Nothing was "
                    "executed and no number was produced."
                ),
            },
            status_code=409,
        )
    package, manifest = session.execute(
        manifest_store=_manifests(), save=request.save
    )
    payload = package.to_dict()
    payload["executed"] = True
    payload["manifest"] = manifest.model_dump(mode="json")
    return JSONResponse(payload)


@app.get("/trace/{manifest_id}")
def trace_endpoint(manifest_id: str, verdict: str = "case") -> dict[str, Any]:
    from .agent import render_trace, trace_number

    pipeline = get_pipeline()
    try:
        manifest = _manifests().load(manifest_id)
        assignments = _results().read(manifest_id)
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    count = sum(1 for a in assignments if a.verdict == verdict)
    chain = trace_number(
        number=count, label=f"{verdict} count", manifest=manifest,
        assignments=assignments, episodes=pipeline.episodes(),
        records=pipeline.records(), verdict=verdict,
    )
    return {
        "manifest_id": manifest_id,
        "number": count,
        "complete": chain.complete,
        "broken_at": chain.broken_at,
        "links": [link.model_dump(mode="json") for link in chain.links],
        "rendered": render_trace(chain),
    }


# --------------------------------------------------------------------------
# Runs and the knowledge layer
# --------------------------------------------------------------------------


@app.get("/runs")
def list_runs(limit: int = Query(25, le=200)) -> dict[str, Any]:
    manifests = _manifests().list()[-limit:]
    return {
        "runs": [
            {
                "manifest_id": m.manifest_id, "created_at": m.created_at,
                "actor": m.actor, "question": m.question,
                "definition": (
                    f"{m.phenotype_definition_id}."
                    f"v{m.phenotype_definition_version}"
                ),
                "definition_hash": m.definition_hash,
                "counts_by_verdict": m.counts_by_verdict,
                "attribute_methods": m.attribute_methods,
                "results_hash": m.results_hash,
                "output_pointer": m.output_pointer,
            }
            for m in manifests
        ]
    }


@app.get("/runs/{manifest_id}")
def get_run(manifest_id: str) -> dict[str, Any]:
    try:
        return _manifests().load(manifest_id).model_dump(mode="json")
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.post("/runs/{manifest_id}/replay")
def replay_run(manifest_id: str) -> dict[str, Any]:
    from .runs import replay

    pipeline = get_pipeline()
    try:
        report, manifest = replay(
            manifest_id, manifest_store=_manifests(),
            data_dir=pipeline.store.root,
            phenotype_dir=pipeline.definitions.directory,
        )
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return {
        "manifest_id": manifest_id,
        "reproduced": report.reproduced,
        "original_results_hash": report.original_hash,
        "replayed_results_hash": report.replayed_hash,
        "differences": report.differences,
        "summary": report.summary(),
        "counts_by_verdict": manifest.counts_by_verdict,
    }


@app.get("/knowledge/status")
def knowledge_status() -> dict[str, Any]:
    pipeline = get_pipeline()
    return KnowledgeRegistry.open(
        _runs_dir(), definitions=pipeline.definitions
    ).status()


# --------------------------------------------------------------------------

if paths.UI_DIR.exists():
    app.mount("/ui", StaticFiles(directory=str(paths.UI_DIR), html=True), name="ui")

    @app.get("/", include_in_schema=False)
    def index() -> FileResponse:
        return FileResponse(str(paths.UI_DIR / "index.html"))
