"""HTTP API.

Thin.  Every endpoint delegates to the same pipeline the CLI uses, so the API
and the CLI cannot disagree about which definition version produced a number.

Two things this API does differently from the obvious design.

**There is no approval gate.**  A compiled specification is returned, and it is
executed.  Approving a specification you cannot independently evaluate is
ceremony; what makes a number checkable is that ``/trace`` walks it back to the
sentence a site wrote, after the fact, by someone who was not in the room.

**Discovery and cohort selection are different endpoints.**  ``/retrieve``
returns episodes that a definition has adjudicated.  ``/discover`` returns
places in documents where a concept is named, and says in the payload that they
are candidates.  A caller cannot reach a denominator from the second one by
adding a parameter.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, Optional

import yaml
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from . import paths
from .catalog import ConfigError
from .ingest import IngestError
from .knowledge import KnowledgeRegistry, ScopeRequired, diff_definitions
from .phenotype.loader import DefinitionError
from .pipeline import Pipeline
from .runs import ManifestStore, ReplayError, ResultStore, execute
from .semantics import SemanticsError

NOTICE = (
    "All data is synthetic and generated by this repository. The extraction "
    "backend is a configurable rule and lexicon baseline unless an LLM backend "
    "was configured; it is not a trained clinical NLP model. Coded terms in "
    "the concept catalogue are illustrative placeholders, not licensed "
    "dictionary content."
)

app = FastAPI(
    title="Adverse event evidence layer",
    version="2.0.0",
    description=(
        "Source-faithful canonical AE records, derived episodes above them, "
        "and versioned phenotype definitions evaluated over the episodes. "
        + NOTICE
    ),
)


@lru_cache(maxsize=1)
def _pipeline_singleton() -> Pipeline:
    return Pipeline.load(store_path=paths.STORE_DB)


def get_pipeline() -> Pipeline:
    try:
        return _pipeline_singleton()
    except (IngestError, ConfigError, SemanticsError) as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


def reset_pipeline() -> None:
    _pipeline_singleton.cache_clear()


def _runs_dir() -> Path:
    return paths.RUNS_DIR


def _manifests() -> ManifestStore:
    return ManifestStore(_runs_dir())


def _results() -> ResultStore:
    return ResultStore(_runs_dir() / "results")


# --------------------------------------------------------------------------
# Request bodies
# --------------------------------------------------------------------------


class BuildRequest(BaseModel):
    refresh: bool = Field(
        default=False, description="Re-normalize and re-extract from source."
    )


class EvaluateRequest(BaseModel):
    definition_id: str = "te_symptomatic_hypoglycemia"
    version: Optional[int] = None
    studies: list[str] = Field(default_factory=list)
    allow_draft: bool = False
    save: bool = True


class AskRequest(BaseModel):
    question: str
    backend: Literal["deterministic", "llm"] = "deterministic"
    save: bool = True


class CandidateRequest(BaseModel):
    definition_id: str
    base_version: int
    changes: dict[str, Any] = Field(
        default_factory=dict,
        description=(
            "Dotted paths to new values, e.g. "
            '{"window.max": 7, "evidence_rules.supported.lab.value": 54}'
        ),
    )
    author: str = "ui"


# --------------------------------------------------------------------------
# Corpus and provenance
# --------------------------------------------------------------------------


@app.get("/api/summary")
def summary() -> dict[str, Any]:
    pipeline = get_pipeline()
    semantics = pipeline.semantics
    return {
        **pipeline.summary(),
        "studies": pipeline.store.studies(),
        "study_semantics": {
            study_id: {
                "label": s.label,
                "representation": s.representation,
                "dictionary": s.dictionary,
                "dictionary_version": s.dictionary_version,
                "glucose_unit": s.glucose_unit,
                "record_splitting": s.record_splitting,
                "narrative_detail": s.narrative_detail,
                "linked_forms": list(s.linked_forms),
                "collected_fields": list(s.collected_fields),
                "note": s.note,
            }
            for study_id, s in sorted(semantics.studies.items())
        },
        "concepts": sorted(pipeline.catalog.concepts),
        "concept_groups": pipeline.catalog.concept_groups,
        "collection_states": collection_state_counts(),
        "notice": NOTICE,
    }


def collection_state_counts() -> dict[str, int]:
    import collections

    pipeline = get_pipeline()
    counts = collections.Counter(
        state
        for record in pipeline.records()
        for state in record.collection_states().values()
    )
    return dict(sorted(counts.items()))


@app.post("/build")
def build(request: BuildRequest) -> dict[str, Any]:
    """Normalize, extract, reconcile, index — the whole deterministic path."""
    pipeline = get_pipeline()
    records = pipeline.records(refresh=request.refresh)
    episodes = pipeline.episodes(refresh=request.refresh)
    index = pipeline.index(refresh=request.refresh)
    violations = [
        {"record_id": r.source_record_id, "fields": r.missing_provenance()}
        for r in records
        if not r.has_full_provenance()
    ]
    return {
        "records": len(records),
        "episodes": len(episodes),
        "documents": index.meta().document_count,
        "mentions": index.meta().mention_count,
        "flagged_for_linkage_review": sum(
            1 for e in episodes if e.linkage_review_required
        ),
        **pipeline.versions(),
        "provenance_violations": violations,
        "backend_notes": list(pipeline.engine().notes),
    }


@app.get("/api/records")
def records(
    study: Optional[str] = None,
    collection_state: list[str] = Query(default=[]),
    limit: int = Query(50, le=500),
) -> dict[str, Any]:
    """Source-faithful canonical records, with what each blank means."""
    pipeline = get_pipeline()
    rows = pipeline.records()
    if study:
        rows = [r for r in rows if r.study_id == study]
    if collection_state:
        wanted = set(collection_state)
        rows = [
            r for r in rows
            if wanted & set(r.collection_states().values())
        ]
    return {
        "count": len(rows),
        "records": [
            {
                "record_id": r.record_id,
                "source_record_id": r.source_record_id,
                "study_id": r.study_id,
                "subject_id": r.subject_id,
                "source_form_id": r.source_form_id,
                "verbatim_term": r.verbatim_term.value,
                "coded_term": r.coded_term.value,
                "dictionary_version": r.dictionary_version,
                "standardized_concept": r.standardized_concept,
                "concept_source": r.concept_source,
                "collection_states": r.collection_states(),
                "narrative_doc_id": r.narrative_doc_id,
                "continuation_of": r.continuation_of,
            }
            for r in rows[:limit]
        ],
    }


@app.get("/api/records/{source_record_id}")
def record(source_record_id: str) -> dict[str, Any]:
    """One record, every field, every state, every span behind it."""
    pipeline = get_pipeline()
    found = next(
        (r for r in pipeline.records() if r.source_record_id == source_record_id), None
    )
    if found is None:
        raise HTTPException(
            status_code=404, detail=f"no record {source_record_id!r}"
        )
    narrative = (
        pipeline.store.narratives.get(found.narrative_doc_id)
        if found.narrative_doc_id else None
    )
    return {
        "record": found.model_dump(mode="json"),
        "fields": {
            name: {
                "value": field.value,
                "collection_state": field.collection_state,
                "structured_state": field.structured_state,
                "source": field.source,
                "confidence": field.confidence,
                "note": field.note,
                "spans": [s.model_dump(mode="json") for s in field.spans],
            }
            for name, field in found.fields().items()
        },
        "narrative": (
            {
                "doc_id": narrative.doc_id,
                "header": narrative.header,
                "text": narrative.full_text,
            }
            if narrative else None
        ),
        "provenance_complete": found.has_full_provenance(),
    }


@app.get("/api/episodes")
def episodes(
    study: Optional[str] = None,
    concept: Optional[str] = None,
    review_only: bool = False,
    limit: int = Query(50, le=500),
) -> dict[str, Any]:
    """Derived episodes. Source records are unchanged beneath them."""
    pipeline = get_pipeline()
    rows = pipeline.episodes()
    if study:
        rows = [e for e in rows if e.study_id == study]
    if concept:
        rows = [e for e in rows if e.standardized_concept == concept]
    if review_only:
        rows = [e for e in rows if e.linkage_review_required]
    return {
        "count": len(rows),
        "episodes": [
            {
                "episode_id": e.episode_id,
                "study_id": e.study_id,
                "subject_id": e.subject_id,
                "standardized_concept": e.standardized_concept,
                "source_record_ids": list(e.source_record_ids),
                "episode_start": (
                    e.episode_start.value.isoformat() if e.episode_start.value else None
                ),
                "peak_severity": e.peak_severity,
                "linkage_rule": e.linkage_rule,
                "linkage_confidence": round(e.linkage_confidence, 4),
                "linkage_review_required": e.linkage_review_required,
                "linkage_note": e.linkage_note,
                "candidate": e.candidate,
            }
            for e in rows[:limit]
        ],
    }


@app.get("/api/episodes/{episode_id}")
def episode(episode_id: str) -> dict[str, Any]:
    pipeline = get_pipeline()
    found = next(
        (e for e in pipeline.episodes() if e.episode_id == episode_id), None
    )
    if found is None:
        raise HTTPException(status_code=404, detail=f"no episode {episode_id!r}")
    by_id = {r.source_record_id: r for r in pipeline.records()}
    return {
        "episode": found.model_dump(mode="json"),
        "field_states": found.field_states,
        "field_notes": found.field_notes,
        "records": [
            by_id[rid].model_dump(mode="json")
            for rid in found.source_record_ids if rid in by_id
        ],
    }


@app.get("/api/documents")
def documents(
    study: Optional[str] = None, limit: int = Query(50, le=500)
) -> dict[str, Any]:
    pipeline = get_pipeline()
    rows = sorted(pipeline.store.narratives.values(), key=lambda n: n.doc_id)
    if study:
        rows = [n for n in rows if n.study_id == study]
    return {
        "count": len(rows),
        "documents": [
            {
                "doc_id": n.doc_id,
                "study_id": n.study_id,
                "subject_id": n.subject_id,
                "preview": n.text[:120],
            }
            for n in rows[:limit]
        ],
    }


@app.get("/api/documents/{doc_id}")
def document(doc_id: str) -> dict[str, Any]:
    """Source text beside every record derived from it."""
    pipeline = get_pipeline()
    narrative = pipeline.store.narratives.get(doc_id)
    if narrative is None:
        raise HTTPException(status_code=404, detail=f"no document {doc_id!r}")
    rows = [r for r in pipeline.records() if r.narrative_doc_id == doc_id]
    return {
        "doc_id": doc_id,
        "study_id": narrative.study_id,
        "subject_id": narrative.subject_id,
        "header": narrative.header,
        "text": narrative.full_text,
        "records": [r.model_dump(mode="json") for r in rows],
        "extractor_version": pipeline.extractor_version,
    }


# --------------------------------------------------------------------------
# Definitions
# --------------------------------------------------------------------------


@app.get("/definitions")
def definitions() -> dict[str, Any]:
    pipeline = get_pipeline()
    return {
        "definitions": [
            {
                "id": d.id,
                "version": d.version,
                "key": d.key,
                "status": d.status,
                "label": d.label,
                "description": d.description,
                "hash": d.definition_hash,
                "body": d.model_dump(mode="json"),
            }
            for d in pipeline.definitions.all()
        ]
    }


@app.get("/definitions/{definition_id}/{version}/yaml", response_class=PlainTextResponse)
def definition_yaml(definition_id: str, version: int) -> str:
    pipeline = get_pipeline()
    try:
        definition = pipeline.definitions.get(definition_id, version, allow_draft=True)
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return Path(definition.source_path).read_text(encoding="utf-8")


@app.get("/definitions/{definition_id}/compare")
def definition_compare(
    definition_id: str,
    left: int,
    right: int,
    scope: Optional[str] = Query(
        default=None,
        description=(
            "Required. The scientific question this comparison serves. The "
            "capability is for evidence reuse, not for auditing past choices."
        ),
    ),
) -> dict[str, Any]:
    """Compare two versions by the episodes each one claims, not by their text."""
    pipeline = get_pipeline()
    try:
        a = pipeline.definitions.get(definition_id, left, allow_draft=True)
        b = pipeline.definitions.get(definition_id, right, allow_draft=True)
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    try:
        comparison = diff_definitions(
            a, b, pipeline.snapshot_id, scope,
            pipeline.evaluate(a), pipeline.evaluate(b),
        )
    except ScopeRequired as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return comparison.to_dict()


@app.post("/definitions/candidate")
def definition_candidate(request: CandidateRequest) -> dict[str, Any]:
    """Render a proposed next version as YAML, without writing anything.

    Editing a control in the UI produces a candidate; it never mutates the
    frozen definition it was derived from.  Publishing is a separate,
    deliberate act performed outside this process.
    """
    pipeline = get_pipeline()
    try:
        base = pipeline.definitions.get(
            request.definition_id, request.base_version, allow_draft=True
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    body = base.model_dump(mode="json", exclude={"definition_hash", "source_path"})
    next_version = pipeline.definitions.next_version(base.id)
    body["version"] = next_version
    body["status"] = "draft"
    body["supersedes"] = base.key
    body["authors"] = [request.author]

    applied: list[str] = []
    for path, value in sorted(request.changes.items()):
        if _apply_change(body, path, value):
            applied.append(f"{path} = {value!r}")
        else:
            raise HTTPException(
                status_code=400, detail=f"no such definition path: {path!r}"
            )

    from .models import PhenotypeDefinition

    try:
        PhenotypeDefinition.model_validate(body)
    except Exception as exc:
        raise HTTPException(
            status_code=400,
            detail=f"the proposed candidate does not validate: {exc}",
        ) from exc

    return {
        "base": base.key,
        "candidate_version": next_version,
        "filename": f"{base.id}.v{next_version}.yaml",
        "applied_changes": applied,
        "yaml": yaml.safe_dump(body, sort_keys=False, allow_unicode=True),
        "note": (
            f"This is a candidate. {base.key} is {base.status} and has not been "
            f"modified. Save this file into config/phenotypes/ to publish it."
        ),
    }


def _apply_change(body: dict[str, Any], path: str, value: Any) -> bool:
    """Set one dotted path inside a definition body.

    Three addressing forms, in order of preference:

    ``window.max``
        plain nested keys
    ``evidence_rules.supported.lab.value``
        an evidence rule by **id**, then a predicate by name found anywhere in
        its ``when`` block. Addressing rules by id rather than list index means
        a candidate keeps its meaning if the rule order changes.
    ``evidence_rules.supported.when.all.0.lab.value``
        the fully explicit path, list indices included
    """
    parts = path.split(".")
    node: Any = body
    for part in parts[:-1]:
        if isinstance(node, list):
            if part.isdigit() and int(part) < len(node):
                node = node[int(part)]
                continue
            match = next(
                (item for item in node
                 if isinstance(item, dict) and item.get("id") == part),
                None,
            )
            if match is None:
                return False
            node = match
            continue
        if isinstance(node, dict):
            if part in node:
                node = node[part]
                continue
            if "when" in node:
                found = _find_predicate(node["when"], part)
                if found is not None:
                    node = found
                    continue
            return False
        return False

    leaf = parts[-1]
    if isinstance(node, dict):
        # The leaf has to already exist. A change that invents a key is a typo
        # in the caller's path, and silently adding it would produce a
        # candidate that quietly differs from the one asked for.
        if leaf not in node:
            return False
        node[leaf] = value
        return True
    if isinstance(node, list) and leaf.isdigit() and int(leaf) < len(node):
        node[int(leaf)] = value
        return True
    return False


def _find_predicate(condition: Any, name: str) -> dict[str, Any] | None:
    """The first predicate body named ``name`` anywhere inside a `when` block."""
    if isinstance(condition, list):
        for item in condition:
            found = _find_predicate(item, name)
            if found is not None:
                return found
        return None
    if not isinstance(condition, dict):
        return None
    for key, value in condition.items():
        if key == name and isinstance(value, dict):
            return value
        found = _find_predicate(value, name)
        if found is not None:
            return found
    return None


# --------------------------------------------------------------------------
# Evaluation and retrieval
# --------------------------------------------------------------------------


@app.post("/evaluate")
def evaluate(request: EvaluateRequest) -> dict[str, Any]:
    pipeline = get_pipeline()
    try:
        definition = pipeline.definition(
            request.definition_id, request.version, allow_draft=request.allow_draft
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    manifest, assignments = execute(
        pipeline, definition,
        studies=request.studies or None,
        actor="api",
        manifest_store=_manifests(),
        result_store=_results(),
        save=request.save,
    )
    if request.save:
        pipeline.index().record_assignments(assignments)
    return {
        "manifest": manifest.model_dump(mode="json"),
        "assignments": [a.model_dump(mode="json") for a in assignments],
        "review_set": [
            a.model_dump(mode="json") for a in assignments if a.verdict == "review"
        ],
    }


@app.get("/retrieve")
def retrieve_endpoint(
    concept: Optional[str] = None,
    group: Optional[str] = None,
    text: Optional[str] = None,
    assertion: list[str] = Query(default=[]),
    evidence_state: list[str] = Query(default=[]),
    verdict: list[str] = Query(default=[]),
    studies: list[str] = Query(default=[]),
    representation: list[str] = Query(default=[]),
    provenance: list[str] = Query(default=[]),
    window_min: Optional[int] = None,
    window_max: Optional[int] = None,
    anchor: Optional[str] = None,
    linkage_review: Optional[bool] = None,
    definition_id: str = "te_symptomatic_hypoglycemia",
    definition_version: Optional[int] = None,
    top_k: int = Query(20, le=1000),
) -> dict[str, Any]:
    """The precise path: adjudicated episodes, usable as a cohort."""
    from .retrieval.query import retrieve

    pipeline = get_pipeline()
    window = (
        (window_min, window_max)
        if window_min is not None and window_max is not None
        else None
    )
    try:
        result = retrieve(
            pipeline.index(), pipeline.catalog,
            concept=concept, group=group, text=text,
            assertion=assertion or None,
            evidence_state=evidence_state or None,
            verdict=verdict or None,
            window=window, anchor=anchor,
            studies=studies or None,
            representation=representation or None,
            provenance=provenance or None,
            linkage_review=linkage_review,
            definition_id=definition_id,
            definition_version=definition_version,
            mode="precise", top_k=top_k,
        )
    except ConfigError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return result.to_dict()


@app.get("/discover")
def discover_endpoint(
    concept: Optional[str] = None,
    group: Optional[str] = None,
    text: Optional[str] = None,
    assertion: list[str] = Query(default=[]),
    studies: list[str] = Query(default=[]),
    match_kind: list[str] = Query(default=[]),
    mode: Literal["lexical", "dense", "hybrid"] = "lexical",
    top_k: int = Query(20, le=1000),
) -> dict[str, Any]:
    """The discovery path: narrative mentions, every one a candidate."""
    from .retrieval.query import discover

    pipeline = get_pipeline()
    try:
        result = discover(
            pipeline.index(), pipeline.catalog,
            concept=concept, group=group, text=text,
            assertion=assertion or None,
            studies=studies or None,
            match_kind=match_kind or None,
            mode=mode, top_k=top_k,
        )
    except ConfigError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    payload = result.to_dict()
    payload["usable_as_cohort"] = False
    payload["cohort_note"] = (
        "A mention is a place in a document where a concept is named, not an "
        "episode that occurred. These enter a cohort through adjudication or a "
        "definition version that claims them, never directly."
    )
    return payload


# --------------------------------------------------------------------------
# Agent
# --------------------------------------------------------------------------


@app.post("/agent/compile")
def agent_compile(request: AskRequest) -> JSONResponse:
    """Compile a question into a specification. Never executes."""
    from .agent import AgentSession

    pipeline = get_pipeline()
    session = AgentSession(pipeline, request.question, backend=request.backend)
    result = session.compile()
    payload = result.to_dict()
    payload["executed"] = False
    return JSONResponse(payload, status_code=200 if result.spec else 409)


@app.post("/agent/ask")
def agent_ask(request: AskRequest) -> JSONResponse:
    """Compile and execute, and return the trace that makes it checkable.

    There is no approval step. A specification the caller cannot independently
    evaluate is not made safer by a click; what makes the number checkable is
    the trace returned with it.
    """
    from .agent import AgentSession

    pipeline = get_pipeline()
    session = AgentSession(pipeline, request.question, backend=request.backend)
    result = session.compile()
    if result.needs_clarification:
        return JSONResponse(
            {
                "executed": False,
                "clarification": result.clarification.model_dump(mode="json"),
                "detail": (
                    "The question leaves a rule underdetermined. Nothing was "
                    "executed and no number was produced."
                ),
            },
            status_code=409,
        )
    package, manifest = session.execute(
        manifest_store=_manifests(), save=request.save
    )
    payload = package.to_dict()
    payload["executed"] = True
    payload["manifest"] = manifest.model_dump(mode="json")
    return JSONResponse(payload)


@app.get("/trace/{manifest_id}")
def trace_endpoint(manifest_id: str, verdict: str = "case") -> dict[str, Any]:
    """Follow a reported number back to the text a site wrote."""
    from .agent import render_trace, trace_number

    pipeline = get_pipeline()
    try:
        manifest = _manifests().load(manifest_id)
        assignments = _results().read(manifest_id)
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    count = sum(1 for a in assignments if a.verdict == verdict)
    chain = trace_number(
        number=count, label=f"{verdict} count", manifest=manifest,
        assignments=assignments, episodes=pipeline.episodes(),
        records=pipeline.records(), verdict=verdict,
    )
    return {
        "manifest_id": manifest_id,
        "number": count,
        "complete": chain.complete,
        "broken_at": chain.broken_at,
        "links": [link.model_dump(mode="json") for link in chain.links],
        "rendered": render_trace(chain),
    }


# --------------------------------------------------------------------------
# Runs and the knowledge layer
# --------------------------------------------------------------------------


@app.get("/runs")
def list_runs(limit: int = Query(25, le=200)) -> dict[str, Any]:
    manifests = _manifests().list()[-limit:]
    return {
        "runs": [
            {
                "manifest_id": m.manifest_id,
                "created_at": m.created_at,
                "actor": m.actor,
                "question": m.question,
                "definition": (
                    f"{m.phenotype_definition_id}.v{m.phenotype_definition_version}"
                ),
                "definition_hash": m.definition_hash,
                "normalizer_version": m.normalizer_version,
                "extractor_version": m.extractor_version,
                "snapshot_id": m.data_snapshot_id,
                "counts_by_verdict": m.counts_by_verdict,
                "results_hash": m.results_hash,
                "output_pointer": m.output_pointer,
            }
            for m in manifests
        ]
    }


@app.get("/runs/{manifest_id}")
def get_run(manifest_id: str) -> dict[str, Any]:
    try:
        manifest = _manifests().load(manifest_id)
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return manifest.model_dump(mode="json")


@app.post("/runs/{manifest_id}/replay")
def replay_run(manifest_id: str) -> dict[str, Any]:
    from .runs import replay

    # Replay against the corpus this process is actually serving, not whatever
    # happens to sit at the default data path.
    pipeline = get_pipeline()
    try:
        report, manifest = replay(
            manifest_id,
            manifest_store=_manifests(),
            data_dir=pipeline.store.root,
            phenotype_dir=pipeline.definitions.directory,
        )
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return {
        "manifest_id": manifest_id,
        "reproduced": report.reproduced,
        "original_results_hash": report.original_hash,
        "replayed_results_hash": report.replayed_hash,
        "differences": report.differences,
        "summary": report.summary(),
        "counts_by_verdict": manifest.counts_by_verdict,
    }


@app.get("/knowledge/status")
def knowledge_status() -> dict[str, Any]:
    """What the registry holds. Empty on day one, and it says so."""
    pipeline = get_pipeline()
    return KnowledgeRegistry.open(
        _runs_dir(), definitions=pipeline.definitions
    ).status()


# --------------------------------------------------------------------------
# Static UI
# --------------------------------------------------------------------------

if paths.UI_DIR.exists():
    app.mount("/ui", StaticFiles(directory=str(paths.UI_DIR), html=True), name="ui")

    @app.get("/", include_in_schema=False)
    def index() -> FileResponse:
        return FileResponse(str(paths.UI_DIR / "index.html"))
