"""HTTP API.

Thin. Every endpoint delegates to the same pipeline the CLI uses, so the API
and the CLI cannot disagree about which definition version produced a number.

Four things this API does deliberately:

**Attributes carry their route.** Every record response says which variable
each value came from, by which method, and — separately — what the source
asserted and whether it said anything at all. In this layer those are part of
the fact rather than metadata about it.

**Assertion and availability are separate query parameters.** There is no
single "missing" filter, because a documented negative and an uncollected
variable are different populations and a combined filter would invite treating
them as one.

**Discovery and cohort selection are different endpoints.** ``/retrieve``
returns adjudicated records; ``/discover`` returns candidates and says so in
the payload. No parameter turns one into the other.

**There is no approval gate.** ``/agent/ask`` compiles, executes, and returns
the trace. What makes a number checkable is that it can be followed back to
source afterwards, by someone who was not in the room. A question that
conflicts with the definition it names returns 409 and no number at all.
"""

from __future__ import annotations

import collections
from functools import lru_cache
from pathlib import Path
from typing import Any, Literal, Optional

import yaml
from fastapi import FastAPI, HTTPException, Query
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel, Field

from . import paths
from .catalog import ConfigError
from .ingest import IngestError
from .knowledge import KnowledgeRegistry, ScopeRequired, diff_definitions
from .models import DENOMINATOR_NOTE
from .phenotype.loader import DefinitionError
from .pipeline import Pipeline
from .profiles import ProfileError
from .runs import ManifestStore, ReplayError, ResultStore, execute
from .silver import SILVER_CAVEATS

DEFINITION = "cutaneous_mucosal"
MODIFIER = "mucosal_involvement"

NOTICE = (
    "All data is synthetic and generated by this repository. The extraction "
    "backend is a configurable rule and lexicon baseline unless an LLM backend "
    "was configured; it is not a trained clinical NLP model. Coded terms in the "
    "concept catalogue are illustrative placeholders, not licensed dictionary "
    "content."
)

app = FastAPI(
    title="Adverse event evidence layer",
    version="4.0.0",
    description=(
        "One clinical modifier, five possible homes, one provenance-bearing "
        "shape, and versioned phenotype definitions evaluated over it. " + NOTICE
    ),
)


@lru_cache(maxsize=1)
def _pipeline_singleton() -> Pipeline:
    return Pipeline.load(store_path=paths.STORE_DB)


def get_pipeline() -> Pipeline:
    try:
        return _pipeline_singleton()
    except (IngestError, ConfigError, ProfileError) as exc:
        raise HTTPException(status_code=503, detail=str(exc)) from exc


def reset_pipeline() -> None:
    _pipeline_singleton.cache_clear()


def _runs_dir() -> Path:
    return paths.RUNS_DIR


def _manifests() -> ManifestStore:
    return ManifestStore(_runs_dir())


def _results() -> ResultStore:
    return ResultStore(_runs_dir() / "results")


def _attribute(attribute: Any) -> dict[str, Any]:
    """One attribute, with the two fields kept apart on the wire too."""
    return {
        "value": attribute.value,
        "assertion": attribute.assertion,
        "availability": attribute.availability,
        "observed": attribute.observed,
        "documented_negative": attribute.documented_negative,
        "method": attribute.method,
        "source": attribute.source,
        "source_variable": attribute.source_variable,
        "confidence": attribute.confidence,
        "versions": attribute.versions,
        "note": attribute.note,
        "prior_availability": attribute.prior_availability,
        "route": attribute.describe_route(),
        "evidence": [s.model_dump(mode="json") for s in attribute.evidence],
    }


# --------------------------------------------------------------------------
# Requests
# --------------------------------------------------------------------------


class BuildRequest(BaseModel):
    refresh: bool = False


class EvaluateRequest(BaseModel):
    definition_id: str = DEFINITION
    version: Optional[int] = None
    studies: list[str] = Field(default_factory=list)
    allow_draft: bool = False
    save: bool = True


class AskRequest(BaseModel):
    question: str
    backend: Literal["deterministic", "llm"] = "deterministic"
    save: bool = True


class CandidateRequest(BaseModel):
    definition_id: str
    base_version: int
    changes: dict[str, Any] = Field(default_factory=dict)
    author: str = "ui"


# --------------------------------------------------------------------------
# Corpus
# --------------------------------------------------------------------------


@app.get("/api/summary")
def summary() -> dict[str, Any]:
    pipeline = get_pipeline()
    records = pipeline.records()
    return {
        **pipeline.summary(),
        "study_ids": pipeline.store.studies(),
        "profiles": {
            profile.profile_id: {
                "study_id": profile.study_id,
                "label": profile.label,
                "reported_term_style": profile.reported_term_style,
                "modifier_homes": profile.home_ids(MODIFIER),
                "dictionary_version": profile.dictionary_version,
                "carries_both": profile.carries_both(MODIFIER),
                "supportability": profile.supportability(MODIFIER)[0],
                "note": profile.note,
            }
            for profile in pipeline.profiles.profiles.values()
        },
        "modifier_catalogues": {
            name: catalogue.value_ids()
            for name, catalogue in pipeline.catalog.modifiers.items()
        },
        "modifier_routes": dict(sorted(collections.Counter(
            (r.modifiers[MODIFIER].method or r.modifiers[MODIFIER].availability)
            for r in records if MODIFIER in r.modifiers
        ).items())),
        "assertions": dict(sorted(collections.Counter(
            (r.modifiers[MODIFIER].assertion or "silent")
            for r in records if MODIFIER in r.modifiers
        ).items())),
        "reconciliation": dict(sorted(collections.Counter(
            r.coded_event.reconciliation for r in records if r.coded_event
        ).items())),
        "notice": NOTICE,
    }


@app.post("/build")
def build(request: BuildRequest) -> dict[str, Any]:
    """Normalize, extract, and index — the whole path."""
    pipeline = get_pipeline()
    records = pipeline.records(refresh=request.refresh)
    index = pipeline.index(refresh=request.refresh)
    violations = [
        {"record_id": r.record_id, "attributes": r.missing_provenance()}
        for r in records if not r.has_full_provenance()
    ]
    return {
        "records": len(records),
        "episodes": len(pipeline.episodes(refresh=request.refresh).episodes),
        "mentions": index.meta().mention_count,
        **pipeline.versions(),
        "extraction": pipeline.engine().stats.to_dict(),
        "provenance_violations": violations,
        "backend_notes": list(pipeline.engine().notes),
    }


@app.get("/api/records")
def records(
    profile: Optional[str] = None,
    assertion: Optional[str] = Query(
        None, description="What the source said: present | absent | uncertain."
    ),
    availability: Optional[str] = Query(
        None, description="Whether the source said anything at all."
    ),
    method: Optional[str] = None,
    reconciliation: Optional[str] = None,
    limit: int = Query(50, le=500),
) -> dict[str, Any]:
    pipeline = get_pipeline()
    rows = pipeline.records()
    if profile:
        rows = [r for r in rows if r.profile == profile]
    if assertion:
        rows = [
            r for r in rows
            if r.modifiers.get(MODIFIER)
            and r.modifiers[MODIFIER].assertion == assertion
        ]
    if availability:
        rows = [
            r for r in rows
            if r.modifiers.get(MODIFIER)
            and r.modifiers[MODIFIER].availability == availability
        ]
    if method:
        rows = [
            r for r in rows
            if r.modifiers.get(MODIFIER)
            and r.modifiers[MODIFIER].method == method
        ]
    if reconciliation:
        rows = [
            r for r in rows
            if r.coded_event and r.coded_event.reconciliation == reconciliation
        ]

    def summarised(record: Any) -> dict[str, Any]:
        modifier = record.modifiers.get(MODIFIER)
        coded = record.coded_event
        return {
            "record_id": record.record_id,
            "source_record_id": record.source_record_id,
            "study_id": record.study_id,
            "subject_id": record.subject_id,
            "profile": record.profile,
            "reported_term": record.reported_term.value,
            "code": coded.code if coded else None,
            "dictionary_version": coded.dictionary_version if coded else None,
            "reconciled_to": coded.reconciled_to if coded else None,
            "reconciliation": coded.reconciliation if coded else None,
            "concept": record.concept_id,
            "modifier_assertion": modifier.assertion if modifier else None,
            "modifier_availability": (
                modifier.availability if modifier else "unresolved"
            ),
            "modifier_value": modifier.value if modifier else None,
            "modifier_method": modifier.method if modifier else None,
            "modifier_source": modifier.source_variable if modifier else None,
            "exposure_offset_days": record.exposure_relation.value,
        }

    return {
        "count": len(rows),
        "records": [summarised(r) for r in rows[:limit]],
        "filter_note": (
            "assertion and availability are separate filters on purpose: an "
            "observed 'absent' is an evaluated negative, and 'not_collected' "
            "is silence. Asking for them together is a different question from "
            "asking for either."
        ),
    }


@app.get("/api/records/{record_id:path}")
def record(record_id: str) -> dict[str, Any]:
    pipeline = get_pipeline()
    found = next(
        (r for r in pipeline.records()
         if r.record_id == record_id or r.source_record_id == record_id),
        None,
    )
    if found is None:
        raise HTTPException(status_code=404, detail=f"no record {record_id!r}")
    documents = pipeline.store.documents_of(found.source_record_id)
    coded = found.coded_event
    return {
        "record_id": found.record_id,
        "source_record_id": found.source_record_id,
        "study_id": found.study_id,
        "subject_id": found.subject_id,
        "profile": found.profile,
        "concept": found.concept_id,
        "coded_event": coded.model_dump(mode="json") if coded else None,
        "normalizer_version": found.normalizer_version,
        "extractor_version": found.extractor_version,
        "attributes": {
            name: _attribute(attribute)
            for name, attribute in found.attributes().items()
        },
        "documents": [
            {"doc_id": d.doc_id, "kind": d.kind, "text": d.full_text}
            for d in documents
        ],
    }


@app.get("/api/episodes")
def episodes(limit: int = Query(50, le=500)) -> dict[str, Any]:
    """The demoted grain. Offered as a view; nothing is evaluated here."""
    pipeline = get_pipeline()
    view = pipeline.episodes()
    return {
        **view.to_dict(),
        "episodes": [e.to_dict() for e in view.episodes[:limit]],
    }


@app.get("/api/supportability")
def supportability(modifier: str = MODIFIER) -> dict[str, Any]:
    """Which studies can answer, decided on metadata before any query runs."""
    pipeline = get_pipeline()
    rows = pipeline.supportability(modifier)
    return {
        "modifier": modifier,
        "studies": rows,
        "note": (
            "Decided on collection metadata alone; no patient record was read "
            "to produce it."
        ),
    }


# --------------------------------------------------------------------------
# Definitions
# --------------------------------------------------------------------------


@app.get("/definitions")
def definitions() -> dict[str, Any]:
    pipeline = get_pipeline()
    return {
        "directory": str(pipeline.definitions.directory),
        "definitions": [
            {
                "id": d.id, "version": d.version, "key": d.key,
                "status": d.status, "label": d.label,
                "hash": d.definition_hash, "supersedes": d.supersedes,
                "concept_set": sorted(d.concept_set.include),
                "dictionary_target": d.concept_set.dictionary_target,
                "accept_methods": d.accepted_methods(),
                "modifiers": [
                    {
                        "name": m.name,
                        "require_assertion": m.require_assertion,
                        "accept_methods": list(m.accept_methods),
                        "on_unavailable": m.on_unavailable,
                    }
                    for m in d.modifiers
                ],
                "verdicts": list(d.verdicts),
            }
            for d in pipeline.definitions.all()
        ],
    }


@app.get(
    "/definitions/{definition_id}/{version}/yaml", response_class=PlainTextResponse
)
def definition_yaml(definition_id: str, version: int) -> str:
    pipeline = get_pipeline()
    try:
        definition = pipeline.definitions.get(
            definition_id, version, allow_draft=True
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return Path(definition.source_path).read_text(encoding="utf-8")


@app.get("/definitions/{definition_id}/compare")
def definition_compare(
    definition_id: str, left: int, right: int, scope: Optional[str] = None
) -> dict[str, Any]:
    """Compare two versions by what each actually claims on this snapshot."""
    pipeline = get_pipeline()
    try:
        a = pipeline.definitions.get(definition_id, left, allow_draft=True)
        b = pipeline.definitions.get(definition_id, right, allow_draft=True)
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    try:
        comparison = diff_definitions(
            a, b, pipeline.snapshot_id, scope,
            pipeline.assignments(a), pipeline.assignments(b),
        )
    except ScopeRequired as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return comparison.to_dict()


@app.post("/definitions/candidate")
def definition_candidate(request: CandidateRequest) -> dict[str, Any]:
    """Render a proposed next version as YAML, without writing anything."""
    from .models import PhenotypeDefinition

    pipeline = get_pipeline()
    try:
        base = pipeline.definitions.get(
            request.definition_id, request.base_version, allow_draft=True
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    body = base.model_dump(
        mode="json", exclude={"definition_hash", "source_path"}, by_alias=True
    )
    next_version = pipeline.definitions.next_version(base.id)
    body["version"] = next_version
    body["status"] = "draft"
    body["supersedes"] = base.key
    body["authors"] = [request.author]

    applied: list[str] = []
    for path, value in sorted(request.changes.items()):
        if _apply_change(body, path, value):
            applied.append(f"{path} = {value!r}")
        else:
            raise HTTPException(
                status_code=400, detail=f"no such definition path: {path!r}"
            )
    try:
        PhenotypeDefinition.model_validate(body)
    except Exception as exc:
        raise HTTPException(
            status_code=400,
            detail=f"the proposed candidate does not validate: {exc}",
        ) from exc
    return {
        "base": base.key,
        "candidate_version": next_version,
        "filename": f"{base.id}.v{next_version}.yaml",
        "applied_changes": applied,
        "yaml": yaml.safe_dump(body, sort_keys=False, allow_unicode=True),
        "note": (
            f"This is a candidate. {base.key} is {base.status} and has not been "
            f"modified. Save this file into config/phenotypes/ to publish it."
        ),
    }


def _apply_change(body: dict[str, Any], path: str, value: Any) -> bool:
    """Set one dotted path inside a definition body.

    A requirement is addressed by name — ``modifiers.mucosal_involvement.
    require_assertion`` — rather than by list index, so a candidate keeps its
    meaning if the order changes. The leaf must already exist: a change that
    invents a key is a typo in the caller's path, and adding it silently would
    produce a candidate that differs from the one asked for.
    """
    parts = path.split(".")
    node: Any = body
    for part in parts[:-1]:
        if isinstance(node, list):
            if part.isdigit() and int(part) < len(node):
                node = node[int(part)]
                continue
            match = next(
                (item for item in node
                 if isinstance(item, dict) and item.get("name") == part),
                None,
            )
            if match is None:
                return False
            node = match
            continue
        if isinstance(node, dict) and part in node:
            node = node[part]
            continue
        return False

    leaf = parts[-1]
    if isinstance(node, dict) and leaf in node:
        node[leaf] = value
        return True
    if isinstance(node, list) and leaf.isdigit() and int(leaf) < len(node):
        node[int(leaf)] = value
        return True
    return False


# --------------------------------------------------------------------------
# Evaluation, retrieval, harnesses
# --------------------------------------------------------------------------


@app.post("/evaluate")
def evaluate(request: EvaluateRequest) -> dict[str, Any]:
    pipeline = get_pipeline()
    try:
        definition = pipeline.definition(
            request.definition_id, request.version, allow_draft=request.allow_draft
        )
    except DefinitionError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc

    manifest, assignments = execute(
        pipeline, definition, studies=request.studies or None, actor="api",
        manifest_store=_manifests(), result_store=_results(), save=request.save,
    )
    if request.save:
        pipeline.index().add_verdicts(assignments)
    return {
        "manifest": manifest.model_dump(mode="json"),
        "denominators": manifest.denominators,
        "denominator_note": DENOMINATOR_NOTE,
        "assignments": [a.model_dump(mode="json") for a in assignments],
        "not_ascertainable": [
            a.model_dump(mode="json") for a in assignments
            if a.verdict == "not_ascertainable"
        ],
    }


@app.get("/retrieve")
def retrieve_endpoint(
    concept: Optional[str] = None,
    assertion: list[str] = Query(default=[]),
    availability: list[str] = Query(default=[]),
    value: list[str] = Query(default=[]),
    method: list[str] = Query(default=[]),
    verdict: list[str] = Query(default=[]),
    studies: list[str] = Query(default=[]),
    reconciliation: list[str] = Query(default=[]),
    top_k: int = Query(50, le=500),
) -> dict[str, Any]:
    """The precise cohort path. No embedding decides membership."""
    pipeline = get_pipeline()
    try:
        result = pipeline.retrieve(
            concept=concept, assertion=assertion or None,
            availability=availability or None, value=value or None,
            method=method or None, verdict=verdict or None,
            studies=studies or None, reconciliation=reconciliation or None,
            top_k=top_k,
        )
    except ConfigError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return result.to_dict()


@app.get("/discover")
def discover_endpoint(
    text: Optional[str] = None,
    modifier: list[str] = Query(default=[]),
    assertion: list[str] = Query(default=[]),
    studies: list[str] = Query(default=[]),
    mode: str = "lexical",
    top_k: int = Query(50, le=500),
) -> dict[str, Any]:
    """The discovery path. Everything it returns is a candidate."""
    pipeline = get_pipeline()
    return pipeline.discover(
        text=text, modifier=modifier or None, assertion=assertion or None,
        studies=studies or None, mode=mode, top_k=top_k,
    ).to_dict()


@app.get("/eval/silver")
def silver_endpoint(modifier: str = MODIFIER) -> dict[str, Any]:
    from .silver import SilverHarness

    pipeline = get_pipeline()
    harness = SilverHarness(pipeline.configs, pipeline.store, pipeline.engine())
    report = harness.run(pipeline.records(), modifier)
    body = report.to_dict()
    body["adjudication_queue"] = report.adjudication_queue()[:50]
    return body


@app.get("/eval/transport")
def transport_endpoint(
    definition_id: str = DEFINITION,
    version: Optional[int] = None,
    holdout: list[str] = Query(default=[]),
) -> dict[str, Any]:
    from .eval.transport import transportability

    pipeline = get_pipeline()
    try:
        definition = pipeline.definition(definition_id, version)
    except DefinitionError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    try:
        return transportability(pipeline, definition, holdout or None)
    except ValueError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc


@app.get("/eval/ablation")
def ablation_endpoint(
    definition_id: str = DEFINITION, version: Optional[int] = None
) -> dict[str, Any]:
    """The experiment that can falsify the proposal. Ends in a decision."""
    from .ablation import run_ablation

    pipeline = get_pipeline()
    try:
        definition = pipeline.definition(definition_id, version)
    except DefinitionError as exc:
        raise HTTPException(status_code=400, detail=str(exc)) from exc
    return run_ablation(
        definition, pipeline.store, pipeline.configs, pipeline.backend_preference
    ).to_dict()


@app.get("/eval/caveats")
def caveats_endpoint() -> dict[str, Any]:
    """The caveats that bound what any of these numbers can be used for."""
    return {
        "silver": list(SILVER_CAVEATS),
        "denominator": DENOMINATOR_NOTE,
        "notice": NOTICE,
    }


# --------------------------------------------------------------------------
# Agent
# --------------------------------------------------------------------------


@app.get("/agent/tools")
def agent_tools() -> dict[str, Any]:
    """The agent's entire callable surface, with schemas and permissions."""
    from .agent.tools import AgentServices

    return {
        "tools": AgentServices.catalogue(),
        "note": (
            "Every call is validated against its input schema before it runs "
            "and its output schema before it returns. There is no SQL surface "
            "and no tool that writes to a source record."
        ),
    }


@app.post("/agent/compile")
def agent_compile(request: AskRequest) -> JSONResponse:
    from .agent import AgentSession

    session = AgentSession(get_pipeline(), request.question, backend=request.backend)
    result = session.compile()
    payload = result.to_dict()
    payload["executed"] = False
    return JSONResponse(payload, status_code=200 if result.spec else 409)


@app.post("/agent/ask")
def agent_ask(request: AskRequest) -> JSONResponse:
    """Compile and execute, and return the trace that makes it checkable."""
    from .agent import AgentSession

    session = AgentSession(get_pipeline(), request.question, backend=request.backend)
    result = session.compile()
    if result.needs_clarification:
        return JSONResponse(
            {
                "executed": False,
                "conflict": result.conflict.model_dump(mode="json"),
                "detail": (
                    "The question conflicts with the definition it names, or "
                    "leaves a rule underdetermined. Nothing was executed and no "
                    "number was produced. The agent binds a definition version "
                    "and does not override it to accommodate a question."
                ),
            },
            status_code=409,
        )
    package, manifest = session.execute(
        manifest_store=_manifests(), save=request.save
    )
    payload = package.to_dict()
    payload["executed"] = True
    payload["manifest"] = manifest.model_dump(mode="json")
    return JSONResponse(payload)


@app.get("/trace/{manifest_id}")
def trace_endpoint(manifest_id: str, verdict: str = "case") -> dict[str, Any]:
    from .agent import render_trace, trace_number

    pipeline = get_pipeline()
    try:
        manifest = _manifests().load(manifest_id)
        assignments = _results().read(manifest_id)
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc

    count = sum(1 for a in assignments if a.verdict == verdict)
    chain = trace_number(
        number=count, label=f"{verdict} count", manifest=manifest,
        assignments=assignments, records=pipeline.records(), verdict=verdict,
    )
    return {
        "manifest_id": manifest_id,
        "number": count,
        "complete": chain.complete,
        "broken_at": chain.broken_at,
        "links": [link.model_dump(mode="json") for link in chain.links],
        "rendered": render_trace(chain),
    }


# --------------------------------------------------------------------------
# Runs and the knowledge layer
# --------------------------------------------------------------------------


@app.get("/runs")
def list_runs(limit: int = Query(25, le=200)) -> dict[str, Any]:
    manifests = _manifests().list()[-limit:]
    return {
        "runs": [
            {
                "manifest_id": m.manifest_id, "created_at": m.created_at,
                "actor": m.actor, "question": m.question,
                "definition": f"{m.definition_id}.v{m.definition_version}",
                "definition_hash": m.definition_hash,
                "counts_by_verdict": m.counts_by_verdict,
                "attribute_methods": m.attribute_methods,
                "results_hash": m.results_hash,
                "output_pointer": m.output_pointer,
            }
            for m in manifests
        ]
    }


@app.get("/runs/{manifest_id}")
def get_run(manifest_id: str) -> dict[str, Any]:
    try:
        return _manifests().load(manifest_id).model_dump(mode="json")
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc


@app.post("/runs/{manifest_id}/replay")
def replay_run(manifest_id: str) -> dict[str, Any]:
    from .runs import replay

    pipeline = get_pipeline()
    try:
        report, manifest = replay(
            manifest_id, manifest_store=_manifests(),
            data_dir=pipeline.store.root,
            phenotype_dir=pipeline.definitions.directory,
        )
    except ReplayError as exc:
        raise HTTPException(status_code=404, detail=str(exc)) from exc
    return {
        "manifest_id": manifest_id,
        "reproduced": report.reproduced,
        "original_results_hash": report.original_hash,
        "replayed_results_hash": report.replayed_hash,
        "differences": report.differences,
        "summary": report.summary(),
        "counts_by_verdict": manifest.counts_by_verdict,
    }


@app.get("/knowledge/status")
def knowledge_status() -> dict[str, Any]:
    pipeline = get_pipeline()
    return KnowledgeRegistry.open(
        _runs_dir(), definitions=pipeline.definitions
    ).status()


# --------------------------------------------------------------------------

if paths.UI_DIR.exists():
    app.mount("/ui", StaticFiles(directory=str(paths.UI_DIR), html=True), name="ui")

    @app.get("/", include_in_schema=False)
    def index() -> FileResponse:
        return FileResponse(str(paths.UI_DIR / "index.html"))


def create_app(data_dir: str | Path | None = None) -> FastAPI:
    """The app, with the pipeline pinned to a chosen snapshot."""
    if data_dir is not None:
        reset_pipeline()
        _pipeline_singleton.__wrapped__.__defaults__ = ()  # type: ignore[attr-defined]

        @lru_cache(maxsize=1)
        def _loader() -> Pipeline:
            return Pipeline.load(data_dir, store_path=paths.STORE_DB)

        globals()["_pipeline_singleton"] = _loader
    return app
