"""Governed execution: manifests, result store, replay.

Every execution writes a ``Manifest``.  The manifest records what was asked,
what was compiled, which versions of everything produced the answer, and a
**pointer** to where the result lives.  It never stores the result payload:
copying outputs into the registry would create a second, uncontrolled result
store with its own drift problem.

The manifest id is derived from its content, so an identical question against
identical inputs yields an identical id, and ``replay`` can check that a prior
run still reproduces — including against a definition version that has since
been superseded, because a superseded version is still a file on disk.
"""

from __future__ import annotations

import datetime as _dt
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

from . import paths
from .hashing import hash_payload
from .models import CaseAssignment, Manifest, PhenotypeDefinition
from .pipeline import Pipeline

STANDING_LIMITATIONS = [
    "All data is synthetic and generated by this repository. No conclusion "
    "here transfers to real patients.",
    "The model path is a configurable rules baseline unless an LLM backend was "
    "configured; the manifest records which one ran.",
    "Counts are per the named definition version only. A different version can "
    "reach different verdicts on the same episodes.",
    "Episode boundaries are a declared assumption. Episodes flagged for linkage "
    "review are reported separately, not folded into the counts.",
    "Coded terms in the concept catalogue are illustrative placeholders, not "
    "licensed dictionary content.",
]


class ReplayError(RuntimeError):
    """Raised when a run cannot be found or reproduced from its manifest."""


def _counts(assignments: Sequence[CaseAssignment], attribute: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for assignment in assignments:
        key = getattr(assignment, attribute)
        counts[key] = counts.get(key, 0) + 1
    return dict(sorted(counts.items()))


def results_payload(assignments: Sequence[CaseAssignment]) -> list[dict[str, Any]]:
    """The canonical representation a results hash is taken over."""
    return [
        a.model_dump(mode="json")
        for a in sorted(assignments, key=lambda a: a.episode_id)
    ]


def compute_manifest_id(
    specification: dict[str, Any],
    definition_hash: str,
    snapshot_id: str,
    versions: dict[str, Any],
) -> str:
    """Content-derived. Nothing time-varying goes in."""
    return hash_payload(
        {
            "specification": specification,
            "definition_hash": definition_hash,
            "snapshot_id": snapshot_id,
            "versions": {
                k: v for k, v in sorted(versions.items())
                if k in ("normalizer_version", "extractor_version",
                         "extraction_backend", "model_version")
            },
        },
        length=16,
    )


@dataclass
class ResultStore:
    """Where results actually live. The manifest only points here."""

    directory: Path

    def __post_init__(self) -> None:
        self.directory = Path(self.directory)

    def path_for(self, manifest_id: str) -> Path:
        return self.directory / f"{manifest_id}.results.json"

    def write(self, manifest_id: str, assignments: Sequence[CaseAssignment]) -> str:
        self.directory.mkdir(parents=True, exist_ok=True)
        target = self.path_for(manifest_id)
        target.write_text(
            json.dumps(results_payload(assignments), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return target.as_uri()

    def read(self, manifest_id: str) -> list[CaseAssignment]:
        target = self.path_for(manifest_id)
        if not target.exists():
            raise ReplayError(
                f"the manifest points at {target}, which does not exist. The "
                f"manifest holds a pointer, not a copy, so a missing result "
                f"file is a real gap rather than a recoverable one."
            )
        return [
            CaseAssignment.model_validate(row)
            for row in json.loads(target.read_text(encoding="utf-8"))
        ]


@dataclass
class ManifestStore:
    directory: Path

    def __post_init__(self) -> None:
        self.directory = Path(self.directory)

    def path_for(self, manifest_id: str) -> Path:
        return self.directory / f"{manifest_id}.json"

    def save(self, manifest: Manifest) -> Path:
        self.directory.mkdir(parents=True, exist_ok=True)
        target = self.path_for(manifest.manifest_id)
        target.write_text(
            json.dumps(manifest.model_dump(mode="json"), indent=2, sort_keys=True)
            + "\n",
            encoding="utf-8",
        )
        return target

    def load(self, manifest_id: str) -> Manifest:
        target = self.path_for(manifest_id)
        if not target.exists():
            known = [p.stem for p in sorted(self.directory.glob("*.json"))]
            raise ReplayError(
                f"no manifest {manifest_id!r} in {self.directory}."
                + (f" Known: {known}" if known else " Nothing has been executed yet.")
            )
        return Manifest.model_validate_json(target.read_text(encoding="utf-8"))

    def list(self) -> list[Manifest]:
        """Every manifest in the directory, skipping anything that is not one.

        A registry directory can accumulate foreign files; refusing to list at
        all because one of them does not parse would make the registry
        unusable for the reason it exists.
        """
        if not self.directory.exists():
            return []
        found: list[Manifest] = []
        for path in sorted(self.directory.glob("*.json")):
            try:
                found.append(self.load(path.stem))
            except Exception:
                continue
        return sorted(found, key=lambda m: (m.created_at, m.manifest_id))


def execute(
    pipeline: Pipeline,
    definition: PhenotypeDefinition,
    *,
    studies: Sequence[str] | None = None,
    question: str = "",
    actor: str = "cli",
    specification: dict[str, Any] | None = None,
    manifest_store: ManifestStore | None = None,
    result_store: ResultStore | None = None,
    save: bool = True,
) -> tuple[Manifest, list[CaseAssignment]]:
    """Run a definition and record the governed execution."""
    assignments = pipeline.evaluate(definition, studies)
    versions = pipeline.versions()

    spec: dict[str, Any] = {
        "definition_id": definition.id,
        "definition_version": definition.version,
        "operates_on": definition.operates_on,
        "concept": definition.concept.primary,
        "studies": sorted(studies) if studies else sorted(pipeline.store.studies()),
    }
    if specification:
        spec.update(specification)

    manifest_id = compute_manifest_id(
        spec, definition.definition_hash, pipeline.snapshot_id, versions
    )
    payload = results_payload(assignments)

    nondeterministic: list[str] = []
    if versions.get("extraction_backend") == "llm":
        nondeterministic.append(
            "clinical detail was extracted by an LLM backend; the extraction "
            "step is not bit-reproducible and the manifest records the model "
            "and prompt versions rather than guaranteeing the output"
        )

    results = result_store or ResultStore(paths.RUNS_DIR / "results")
    pointer = results.write(manifest_id, assignments) if save else ""

    manifest = Manifest(
        manifest_id=manifest_id,
        created_at=_dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        actor=actor,
        question=question,
        specification=spec,
        phenotype_definition_id=definition.id,
        phenotype_definition_version=definition.version,
        definition_hash=definition.definition_hash,
        definition_status=definition.status,
        cohort_specification={
            "studies": spec["studies"],
            "subjects": len(pipeline.cohort(studies)),
            "episodes": len(assignments),
        },
        data_snapshot_id=pipeline.snapshot_id,
        terminology_versions=versions["terminology_versions"],
        normalizer_version=versions["normalizer_version"],
        extractor_version=versions["extractor_version"],
        model_version=versions.get("model_version"),
        prompt_version="extract-prompt-1",
        analysis_method="phenotype_evaluation",
        parameters={"backend": versions.get("extraction_backend")},
        validation_status="unvalidated",
        output_pointer=pointer,
        results_hash=hash_payload(payload, length=32),
        counts_by_state=_counts(assignments, "evidence_state"),
        counts_by_verdict=_counts(assignments, "verdict"),
        deterministic=not nondeterministic,
        nondeterministic_paths=nondeterministic,
        limitations=list(STANDING_LIMITATIONS),
    )
    if save:
        (manifest_store or ManifestStore(paths.RUNS_DIR)).save(manifest)
    return manifest, assignments


@dataclass
class ReplayReport:
    manifest_id: str
    reproduced: bool
    original_hash: str
    replayed_hash: str
    differences: list[str]

    def summary(self) -> str:
        if self.reproduced:
            return (
                f"run {self.manifest_id} reproduced exactly "
                f"(results hash {self.original_hash})"
            )
        return f"run {self.manifest_id} did NOT reproduce: " + "; ".join(
            self.differences
        )


def replay(
    manifest_id: str,
    *,
    manifest_store: ManifestStore | None = None,
    data_dir: str | Path | None = None,
    phenotype_dir: str | Path | None = None,
) -> tuple[ReplayReport, Manifest]:
    """Re-execute a recorded run and check it against what was recorded.

    Each input is checked separately, so a failure says *which* one moved: the
    data, the deterministic config, the extraction config, or the definition.
    """
    store = manifest_store or ManifestStore(paths.RUNS_DIR)
    original = store.load(manifest_id)
    differences: list[str] = []

    pipeline = Pipeline.load(data_dir, phenotype_dir=phenotype_dir)
    versions = pipeline.versions()
    for name, recorded in (
        ("data snapshot", original.data_snapshot_id),
        ("normalizer version", original.normalizer_version),
        ("extractor version", original.extractor_version),
    ):
        key = {
            "data snapshot": "snapshot_id",
            "normalizer version": "normalizer_version",
            "extractor version": "extractor_version",
        }[name]
        if versions[key] != recorded:
            differences.append(
                f"{name} differs (recorded {recorded}, now {versions[key]})"
            )

    definition = pipeline.definitions.get(
        original.phenotype_definition_id,
        original.phenotype_definition_version,
        allow_draft=True,
    )
    if definition.definition_hash != original.definition_hash:
        differences.append(
            f"definition {definition.key} has changed on disk "
            f"(recorded {original.definition_hash}, now {definition.definition_hash})"
        )

    replayed, _assignments = execute(
        pipeline, definition,
        studies=original.specification.get("studies"),
        question=original.question,
        actor=original.actor,
        specification={
            k: v for k, v in original.specification.items()
            if k not in ("definition_id", "definition_version", "studies",
                         "concept", "operates_on")
        },
        save=False,
    )
    if replayed.results_hash != original.results_hash:
        differences.append(
            f"results hash differs (recorded {original.results_hash}, "
            f"replayed {replayed.results_hash})"
        )
    if replayed.manifest_id != original.manifest_id:
        differences.append(
            f"manifest id differs (recorded {original.manifest_id}, "
            f"replayed {replayed.manifest_id})"
        )

    return (
        ReplayReport(
            manifest_id=manifest_id,
            reproduced=not differences,
            original_hash=original.results_hash,
            replayed_hash=replayed.results_hash,
            differences=differences,
        ),
        replayed,
    )
