"""Run manifests and replay.

Every run records three hashes plus the resolved spec and the exact rule that
decided each subject:

``extractor_version``  code version plus extraction and concept config
``definition_hash``    content hash of the phenotype definition file
``snapshot_id``        hash of the input data

The run id is itself derived from those, so re-running identical inputs yields
the same id.  ``replay`` re-executes and compares the result hash, which is what
makes "reproduces a prior run byte-for-byte" a checkable claim rather than an
aspiration — including against a definition version that has since been
superseded, because a superseded version is still a file on disk.
"""

from __future__ import annotations

import datetime as _dt
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Sequence

from . import paths
from .hashing import canonical_json, hash_payload
from .models import CaseAssignment, PhenotypeDefinition, RunManifest
from .pipeline import Pipeline

#: Stated on every run. These are limits of the system, not of a particular run.
STANDING_LIMITATIONS = [
    "All data is synthetic and generated by this repository. No conclusion here "
    "transfers to real patients.",
    "The extractor is a configurable lexicon and rule baseline, not a trained "
    "clinical NLP model. Recall depends on the surface forms present in "
    "concepts.yaml.",
    "Counts are per the named definition version only. A different version can "
    "assign different verdicts to the same event objects.",
    "MedDRA terms in the concept catalogue are illustrative placeholders, not "
    "licensed dictionary content.",
]


class ReplayError(RuntimeError):
    """Raised when a run cannot be reproduced from its manifest."""


def _counts(assignments: Sequence[CaseAssignment], attribute: str) -> dict[str, int]:
    counts: dict[str, int] = {}
    for assignment in assignments:
        key = getattr(assignment, attribute)
        counts[key] = counts.get(key, 0) + 1
    return dict(sorted(counts.items()))


def results_payload(assignments: Sequence[CaseAssignment]) -> list[dict[str, Any]]:
    """The canonical, order-stable representation a run hash is taken over."""
    return [
        a.model_dump(mode="json")
        for a in sorted(assignments, key=lambda a: a.subject_id)
    ]


def compute_run_id(
    spec: dict[str, Any],
    extractor_version: str,
    definition_hash: str,
    snapshot_id: str,
) -> str:
    """Content-derived run id.

    Nothing time-varying goes in, so identical inputs produce an identical id
    and the stability check becomes trivial to state.
    """
    return hash_payload(
        {
            "spec": spec,
            "extractor_version": extractor_version,
            "definition_hash": definition_hash,
            "snapshot_id": snapshot_id,
        },
        length=16,
    )


def execute(
    pipeline: Pipeline,
    definition: PhenotypeDefinition,
    *,
    studies: Sequence[str] | None = None,
    spec_extra: dict[str, Any] | None = None,
    limitations: Sequence[str] | None = None,
) -> RunManifest:
    """Evaluate a definition and build its run manifest."""
    assignments = pipeline.evaluate(definition, studies)
    spec: dict[str, Any] = {
        "definition_id": definition.id,
        "definition_version": definition.version,
        "studies": sorted(studies) if studies else sorted(pipeline.store.studies()),
        "concept": definition.concept.primary,
    }
    if spec_extra:
        spec.update(spec_extra)

    run_id = compute_run_id(
        spec, pipeline.extractor_version, definition.definition_hash,
        pipeline.snapshot_id,
    )
    payload = results_payload(assignments)
    nondeterministic: list[str] = []
    if spec.get("backend") == "llm":
        nondeterministic.append(
            "agent spec compiled by an LLM backend; the compiled spec is "
            "recorded here, but the compilation step is not reproducible"
        )

    return RunManifest(
        run_id=run_id,
        created_at=_dt.datetime.now(_dt.timezone.utc).isoformat(timespec="seconds"),
        spec=spec,
        extractor_version=pipeline.extractor_version,
        definition_id=definition.id,
        definition_version=definition.version,
        definition_hash=definition.definition_hash,
        definition_status=definition.status,
        snapshot_id=pipeline.snapshot_id,
        deterministic=not nondeterministic,
        nondeterministic_paths=nondeterministic,
        counts_by_state=_counts(assignments, "evidence_state"),
        counts_by_verdict=_counts(assignments, "verdict"),
        assignments=sorted(assignments, key=lambda a: a.subject_id),
        results_hash=hash_payload(payload, length=32),
        limitations=list(limitations or STANDING_LIMITATIONS),
    )


# --------------------------------------------------------------------------
# Persistence
# --------------------------------------------------------------------------


class RunStore:
    def __init__(self, directory: str | Path | None = None):
        self.directory = Path(directory or paths.RUNS_DIR)

    def path_for(self, run_id: str) -> Path:
        return self.directory / f"{run_id}.json"

    def save(self, manifest: RunManifest) -> Path:
        self.directory.mkdir(parents=True, exist_ok=True)
        target = self.path_for(manifest.run_id)
        target.write_text(
            json.dumps(manifest.model_dump(mode="json"), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        return target

    def load(self, run_id: str) -> RunManifest:
        target = self.path_for(run_id)
        if not target.exists():
            known = [p.stem for p in sorted(self.directory.glob("*.json"))]
            raise ReplayError(
                f"no run {run_id!r} in {self.directory}."
                + (f" Known runs: {known}" if known else " No runs recorded yet.")
            )
        return RunManifest.model_validate_json(target.read_text(encoding="utf-8"))

    def list(self) -> list[RunManifest]:
        if not self.directory.exists():
            return []
        return sorted(
            (self.load(p.stem) for p in self.directory.glob("*.json")),
            key=lambda m: (m.created_at, m.run_id),
        )


@dataclass
class ReplayReport:
    run_id: str
    reproduced: bool
    original_hash: str
    replayed_hash: str
    differences: list[str]

    def summary(self) -> str:
        if self.reproduced:
            return (
                f"run {self.run_id} reproduced exactly "
                f"(results hash {self.original_hash})"
            )
        return (
            f"run {self.run_id} did NOT reproduce: "
            + "; ".join(self.differences)
        )


def replay(
    run_id: str,
    *,
    run_store: RunStore | None = None,
    data_dir: str | Path | None = None,
    phenotype_dir: str | Path | None = None,
) -> tuple[ReplayReport, RunManifest]:
    """Re-execute a recorded run and check it against what was recorded.

    Each of the three hashes is checked separately so that a failure says which
    input moved: the data, the config, or the definition.
    """
    store = run_store or RunStore()
    original = store.load(run_id)
    differences: list[str] = []

    pipeline = Pipeline.load(data_dir, phenotype_dir=phenotype_dir)
    if pipeline.snapshot_id != original.snapshot_id:
        differences.append(
            f"data snapshot differs (recorded {original.snapshot_id}, "
            f"now {pipeline.snapshot_id})"
        )
    if pipeline.extractor_version != original.extractor_version:
        differences.append(
            f"extractor version differs (recorded {original.extractor_version}, "
            f"now {pipeline.extractor_version})"
        )

    definition = pipeline.definitions.get(
        original.definition_id, original.definition_version, allow_draft=True
    )
    if definition.definition_hash != original.definition_hash:
        differences.append(
            f"definition {definition.key} has changed on disk "
            f"(recorded {original.definition_hash}, now {definition.definition_hash})"
        )

    replayed = execute(
        pipeline,
        definition,
        studies=original.spec.get("studies"),
        spec_extra={
            k: v for k, v in original.spec.items()
            if k not in ("definition_id", "definition_version", "studies", "concept")
        },
        limitations=original.limitations,
    )
    if replayed.results_hash != original.results_hash:
        differences.append(
            f"results hash differs (recorded {original.results_hash}, "
            f"replayed {replayed.results_hash})"
        )
    if replayed.run_id != original.run_id:
        differences.append(
            f"run id differs (recorded {original.run_id}, replayed {replayed.run_id})"
        )

    report = ReplayReport(
        run_id=run_id,
        reproduced=not differences,
        original_hash=original.results_hash,
        replayed_hash=replayed.results_hash,
        differences=differences,
    )
    return report, replayed
